<?php
declare(strict_types=1);

namespace Cybermaps\Audit;

use Cybermaps\Core\ProtocolOutput;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Serializes one saved audit snapshot without re-reading live content.
 */
final class AuditExporter {
	/**
	 * @param array<string,mixed> $run Hydrated saved run.
	 */
	public function json( array $run ): string {
		return ProtocolOutput::json( $run ) . "\n";
	}

	/**
	 * @param array<string,mixed> $run Hydrated saved run.
	 */
	public function csv( array $run ): string {
		$output = '';
		foreach ( $this->csv_chunks( $run ) as $chunk ) {
			$output .= $chunk;
		}
		return $output;
	}

	/**
	 * Yield byte-identical CSV chunks without constructing a second complete
	 * response string in the download controller.
	 *
	 * @param array<string,mixed> $run Hydrated saved run.
	 * @return \Generator<int,string>
	 */
	public function csv_chunks( array $run ): \Generator {
		yield "\xEF\xBB\xBF" . $this->csv_header();
		foreach ( (array) ( $run['findings'] ?? array() ) as $finding ) {
			yield $this->csv_finding_row( $run, $finding );
		}
	}

	private function csv_header(): string {
		return $this->csv_row( array( __( 'Run ID', 'cybermaps' ), __( 'Resource Key', 'cybermaps' ), __( 'Post Type', 'cybermaps' ), __( 'Object ID', 'cybermaps' ), __( 'Title', 'cybermaps' ), __( 'URL', 'cybermaps' ), __( 'Finding', 'cybermaps' ), __( 'Severity', 'cybermaps' ), __( 'Summary', 'cybermaps' ), __( 'Evidence', 'cybermaps' ), __( 'Recommendation', 'cybermaps' ) ) );
	}

	/** @param array<string,mixed> $run @param array<string,mixed> $finding */
	private function csv_finding_row( array $run, array $finding ): string {
		return $this->csv_row( array( (int) $this->field( $run, 'id', 0 ), (string) $this->field( $finding, 'resource_key' ), (string) $this->field( $finding, 'post_type' ), (int) $this->field( $finding, 'object_id', 0 ), (string) $this->field( $finding, 'title' ), (string) $this->field( $finding, 'url' ), (string) $this->field( $finding, 'finding_key' ), (string) $this->field( $finding, 'severity' ), (string) $this->field( $finding, 'summary' ), (string) wp_json_encode( $this->field( $finding, 'evidence', array() ), JSON_UNESCAPED_SLASHES ), (string) $this->field( $finding, 'recommendation' ) ) );
	}

	/** @param array<string,mixed> $record */
	private function field( array $record, string $key, mixed $fallback = '' ): mixed {
		return $record[ $key ] ?? $fallback;
	}

	/**
	 * @param array<string,mixed> $run Hydrated saved run.
	 */
	public function html( array $run ): string {
		$identity           = ReportPresentation::identity();
		$completed          = (string) ( $run['completed_gmt'] ?? '' );
		$findings           = (array) ( $run['findings'] ?? array() );
		$diff               = (array) ( $run['diff'] ?? array() );
		$has_baseline       = (int) ( $diff['baseline_run_id'] ?? 0 ) > 0;
		$filter             = sanitize_key( (string) ( $run['report_filter'] ?? '' ) );
		$catalog            = self::finding_catalog();
		$title              = isset( $catalog[ $filter ] )
			? $catalog[ $filter ]['report_title']
			: __( 'Content Intelligence Report', 'cybermaps' );
		$counts             = array_fill_keys( array_keys( $catalog ), 0 );
		$rows               = $this->finding_rows( $findings, $catalog, $counts );
		$logo               = '' !== (string) $identity['agency_logo']
			? '<img src="' . esc_url( (string) $identity['agency_logo'] ) . '" alt="">'
			: '';
		$prepared_by        = $this->prepared_by( $identity );
		$credit             = '<a href="https://cybermaps.dev" target="_blank" rel="noopener noreferrer">'
			. esc_html__( 'Generated by CYBER MAPS', 'cybermaps' )
			. '</a>';
		$action_cards       = '';
		$report_catalog     = isset( $catalog[ $filter ] ) ? array( $filter => $catalog[ $filter ] ) : $catalog;
		$action_cards       = $this->action_cards( $report_catalog, $counts );
		$comparison_metrics = $this->comparison_metrics( $has_baseline, $diff );
		$analysis_notice    = $this->analysis_notice( $run );

		$document = '<!doctype html><html lang="' . esc_attr( ReportPresentation::language() ) . '"><head><meta charset="utf-8">'
			. '<meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>'
			. esc_html( $title ) . '</title>' . ReportPresentation::stylesheet_markup() . '</head><body class="' . esc_attr( ReportPresentation::theme_class() ) . '"><main class="report">'
			. '<header><div class="brand">' . $logo . '<div><p>' . esc_html( (string) $identity['site_name'] ) . '</p><h1>' . esc_html( $title )
			. '</h1></div></div><div class="meta"><span>'
			. esc_html__( 'Completed', 'cybermaps' ) . ': ' . esc_html( $completed ) . ' GMT</span><span>'
			. esc_html( (string) $identity['site_url'] ) . '</span>' . $prepared_by . '</div></header>'
			. '<div class="report-body"><div class="metrics"><div class="metric"><span>' . esc_html__( 'Resources reviewed', 'cybermaps' ) . '</span><strong>'
			. (int) ( $run['resource_count'] ?? 0 ) . '</strong></div><div class="metric"><span>' . esc_html__( 'Current findings', 'cybermaps' ) . '</span><strong>'
			. count( $findings ) . '</strong></div>' . $comparison_metrics . '</div>' . $analysis_notice
			. '<section><div class="section-heading"><p>' . esc_html__( 'Content priorities', 'cybermaps' ) . '</p><h2>' . esc_html__( 'Action inventory', 'cybermaps' )
			. '</h2></div><div class="actions">' . $action_cards . '</div></section>'
			. '<section><div class="section-heading"><p>' . esc_html__( 'Content details', 'cybermaps' ) . '</p><h2>' . esc_html__( 'Findings and recommendations', 'cybermaps' )
			. '</h2></div><p class="notice">' . esc_html__( 'Measurements capture visible text, media, stored internal links, and assigned navigation in WordPress at report time, using the saved policy for a clear, repeatable action plan.', 'cybermaps' )
			. '</p><div class="table-wrap"><table><thead><tr><th>' . esc_html__( 'Resource', 'cybermaps' ) . '</th><th>' . esc_html__( 'Title', 'cybermaps' )
			. '</th><th>' . esc_html__( 'Finding', 'cybermaps' ) . '</th><th>' . esc_html__( 'Measurement', 'cybermaps' ) . '</th><th>'
			. esc_html__( 'Recommended review', 'cybermaps' ) . '</th></tr></thead><tbody>' . $rows . '</tbody></table></div></section></div><footer>'
			. $credit . '</footer></main></body></html>';

		return ProtocolOutput::report_html( $document );
	}

	/** @param array<int,mixed> $findings @param array<string,array<string,string>> $catalog @param array<string,int> $counts */
	private function finding_rows( array $findings, array $catalog, array &$counts ): string {
		$rows = '';
		foreach ( $findings as $finding ) {
			$finding_key = (string) ( $finding['finding_key'] ?? '' );
			if ( isset( $counts[ $finding_key ] ) ) {
				++$counts[ $finding_key ];
			}
			$rows .= $this->finding_row( $finding, $finding_key, $catalog );
		}
		return '' !== $rows ? $rows : '<tr><td colspan="5">' . esc_html__( 'No findings were recorded for this report.', 'cybermaps' ) . '</td></tr>';
	}

	/** @param array<string,mixed> $finding @param array<string,array<string,string>> $catalog */
	private function finding_row( array $finding, string $finding_key, array $catalog ): string {
		return '<tr><td>' . esc_html( (string) ( $finding['post_type'] ?? '' ) ) . ' #' . (int) ( $finding['object_id'] ?? 0 ) . '</td>'
			. '<td><a href="' . esc_url( (string) ( $finding['url'] ?? '' ) ) . '">' . esc_html( (string) ( $finding['title'] ?? '' ) ) . '</a></td>'
			. '<td><span class="finding finding-' . esc_attr( $finding_key ) . '">' . esc_html( $catalog[ $finding_key ]['label'] ?? $finding_key ) . '</span></td>'
			. '<td>' . esc_html( (string) ( $finding['summary'] ?? '' ) ) . '</td>'
			. '<td>' . esc_html( (string) ( $finding['recommendation'] ?? '' ) ) . '</td></tr>';
	}

	/** @param array<string,string|bool> $identity */
	private function prepared_by( array $identity ): string {
		if ( '' === (string) $identity['agency_name'] ) {
			return '';
		}
		$name = esc_html( (string) $identity['agency_name'] );
		if ( '' !== (string) $identity['agency_url'] ) {
			$name = '<a href="' . esc_url( (string) $identity['agency_url'] ) . '">' . $name . '</a>';
		}
		return '<span>' . esc_html__( 'Prepared by', 'cybermaps' ) . ' ' . $name . '</span>';
	}

	/** @param array<string,array<string,string>> $catalog @param array<string,int> $counts */
	private function action_cards( array $catalog, array $counts ): string {
		$cards = '';
		foreach ( $catalog as $key => $meta ) {
			$cards .= '<div class="action action-' . esc_attr( $key ) . '"><span>' . esc_html( $meta['label'] ) . '</span><strong>'
				. (int) $counts[ $key ] . '</strong><small>' . esc_html( $meta['description'] ) . '</small></div>';
		}
		return $cards;
	}

	/** @param array<string,mixed> $diff */
	private function comparison_metrics( bool $has_baseline, array $diff ): string {
		if ( ! $has_baseline ) {
			return '<div class="metric metric-good"><span>' . esc_html__( 'Comparison', 'cybermaps' ) . '</span><strong>'
				. esc_html__( 'Baseline', 'cybermaps' ) . '</strong></div>';
		}
		return '<div class="metric metric-good"><span>' . esc_html__( 'Resolved since baseline', 'cybermaps' ) . '</span><strong>'
			. count( (array) ( $diff['resolved'] ?? array() ) ) . '</strong></div><div class="metric"><span>'
			. esc_html__( 'Added since baseline', 'cybermaps' ) . '</span><strong>'
			. count( (array) ( $diff['added'] ?? array() ) ) . '</strong></div>';
	}

	/**
	 * @return array<string,array{label:string,description:string,report_title:string}>
	 */
	public static function finding_catalog(): array {
		return array(
			'thin_content'     => array(
				'label'        => __( 'Thin content', 'cybermaps' ),
				'description'  => __( 'Visible text below the configured policy minimum.', 'cybermaps' ),
				'report_title' => __( 'Thin Content Action Report', 'cybermaps' ),
			),
			'stale_content'    => array(
				'label'        => __( 'Freshness review', 'cybermaps' ),
				'description'  => __( 'Content beyond its configured review interval.', 'cybermaps' ),
				'report_title' => __( 'Content Freshness Action Report', 'cybermaps' ),
			),
			'missing_media'    => array(
				'label'        => __( 'Media review', 'cybermaps' ),
				'description'  => __( 'Content without detected stored media where policy requests review.', 'cybermaps' ),
				'report_title' => __( 'Media Opportunity Action Report', 'cybermaps' ),
			),
			'potential_orphan' => array(
				'label'        => __( 'Potential orphan', 'cybermaps' ),
				'description'  => __( 'No stored page or assigned navigation item links to the resource.', 'cybermaps' ),
				'report_title' => __( 'Potential Orphan Content Action Report', 'cybermaps' ),
			),
			'no_homepage_path' => array(
				'label'        => __( 'No homepage path', 'cybermaps' ),
				'description'  => __( 'Links exist, but the local graph has no path from the homepage or assigned navigation.', 'cybermaps' ),
				'report_title' => __( 'Homepage Reachability Action Report', 'cybermaps' ),
			),
			'deeply_linked'    => array(
				'label'        => __( 'Three-plus clicks deep', 'cybermaps' ),
				'description'  => __( 'The shortest stored path is at least three clicks from the homepage.', 'cybermaps' ),
				'report_title' => __( 'Internal Link Depth Action Report', 'cybermaps' ),
			),
		);
	}

	/** @param array<string,mixed> $run Hydrated saved run. */
	private function analysis_notice( array $run ): string {
		$analysis = is_array( $run['analysis'] ?? null ) ? $run['analysis'] : array();
		if ( InternalLinkAnalyzer::ANALYSIS_VERSION !== (int) ( $analysis['internal_link_version'] ?? 0 ) ) {
			return '';
		}

		$message = sprintf(
			/* translators: 1: resource count, 2: unique content-link count, 3: assigned-navigation reference count. */
			__( 'Local link coverage: %1$d stored resources, %2$d unique content links, and %3$d assigned navigation references.', 'cybermaps' ),
			(int) ( $analysis['resource_count'] ?? 0 ),
			(int) ( $analysis['edge_count'] ?? 0 ),
			(int) ( $analysis['navigation_references'] ?? 0 )
		);
		if ( empty( $analysis['complete'] ) ) {
			$message .= ' ' . __( 'The bounded scan was incomplete, so Cybermaps suppressed internal-link findings.', 'cybermaps' );
		} elseif ( empty( $analysis['depth_available'] ) ) {
			$message .= ' ' . __( 'Homepage click depth could not be established from local WordPress data.', 'cybermaps' );
		}

		return '<p class="notice">' . esc_html( $message ) . '</p>';
	}

	/**
	 * @param array<int,mixed> $fields Fields.
	 */
	private function csv_row( array $fields ): string {
		$escaped = array_map(
			static function ( mixed $field ): string {
				$value = (string) $field;
				if ( 1 === preg_match( '/^[\x00-\x20]*[=+\-@]/', $value ) ) {
					$value = "'" . $value;
				}
				return '"' . str_replace( '"', '""', $value ) . '"';
			},
			$fields
		);
		return implode( ',', $escaped ) . "\r\n";
	}
}
