<?php
declare(strict_types=1);

namespace Cybermaps\Tests\Architecture;

use PHPUnit\Framework\TestCase;

class ExternalServicesTest extends TestCase {
	public function test_generated_reports_do_not_load_google_fonts(): void {
		$source = (string) file_get_contents(
			dirname( __DIR__, 2 ) . '/src/Audit/AuditExporter.php'
		);

		$this->assertStringNotContainsString( 'fonts.googleapis.com', $source );
	}

	public function test_indexnow_disclosure_uses_current_terms_url(): void {
		$readme = (string) file_get_contents( dirname( __DIR__, 2 ) . '/readme.txt' );

		$this->assertStringContainsString( 'https://www.indexnow.org/terms', $readme );
		$this->assertStringNotContainsString( 'https://www.indexnow.org/privacypolicy', $readme );
		$this->assertStringContainsString(
			'must proxy or publish Cybermaps\' generated `/{key}.txt` verification path',
			$readme
		);
	}

	public function test_public_delivery_checks_are_disclosed_with_runtime_headers(): void {
		$root   = dirname( __DIR__, 2 );
		$readme = (string) file_get_contents( $root . '/readme.txt' );
		$source = (string) file_get_contents( $root . '/src/Admin/DiscoveryStatus.php' );

		$this->assertStringContainsString( '= Public delivery checks =', $readme );
		$this->assertStringContainsString( '`X-Cybermaps-Diagnostic: 1`', $readme );
		$this->assertStringContainsString( 'Frontend Base URL', $readme );
		$this->assertStringContainsString( 'wp_safe_remote_get(', $source );
		$this->assertStringContainsString( 'wp_safe_remote_head(', $source );
		$this->assertStringContainsString( "'X-Cybermaps-Diagnostic'", $source );
		$this->assertStringContainsString( 'public-endpoint-health', $source );
		$this->assertStringContainsString( 'api-catalog-health', $source );
	}

	public function test_readme_discloses_both_local_rate_limiters(): void {
		$root   = dirname( __DIR__, 2 );
		$readme = (string) file_get_contents( $root . '/readme.txt' );
		$search = (string) file_get_contents( $root . '/src/Discovery/Search.php' );

		$this->assertStringContainsString( 'use local 60-second rate limits', $readme );
		$this->assertStringContainsString( 'REST search stores neither raw IPs nor queries', $readme );
		$this->assertStringContainsString( 'AtomicMinuteCounter::requester_bucket', $search );
		$this->assertStringContainsString( 'AtomicMinuteCounter::increment', $search );
	}

	public function test_websub_discovery_headers_do_not_html_encode_validated_urls(): void {
		$source = (string) file_get_contents(
			dirname( __DIR__, 2 ) . '/src/Discovery/WebSub.php'
		);

		$this->assertStringContainsString(
			'URLManager::sanitize_http_url( $topic_url )',
			$source
		);
		$this->assertStringContainsString(
			'URLManager::sanitize_http_url( $line )',
			$source
		);
		$this->assertStringContainsString(
			"header( 'Link: <' . \$topic_url . '>; rel=\"self\"; type=\"application/feed+json\"', false )",
			$source
		);
		$this->assertStringContainsString(
			"header( 'Link: <' . \$hub . '>; rel=\"hub\"', false )",
			$source
		);
		$this->assertStringNotContainsString( 'esc_url(', $source );
	}

	public function test_public_sitemap_has_no_unapproved_credit_or_inline_script(): void {
		$root      = dirname( __DIR__, 2 );
		$xsl       = (string) file_get_contents( $root . '/assets/xsl/sitemap.xsl' );

		$this->assertStringContainsString(
			'This sitemap index was generated by CYBER MAPS to help with search engine indexing.',
			$xsl
		);
		$this->assertStringNotContainsString( 'cybermaps.dev', $xsl );
		$this->assertStringNotContainsString( '<script', $xsl );
	}

	public function test_administrator_generated_reports_use_the_requested_cybermaps_credit(): void {
		$root      = dirname( __DIR__, 2 );
		$reporting = (string) file_get_contents( $root . '/src/Audit/AuditExporter.php' );
		$settings  = (string) file_get_contents( $root . '/src/Admin/Settings/Tabs/ContentReview.php' );

		$this->assertStringContainsString( 'Generated by CYBER MAPS', $reporting );
		$this->assertStringContainsString( 'https://cybermaps.dev', $reporting );
		$this->assertStringNotContainsString( 'show_cybermaps_attribution', $settings );
		$this->assertStringNotContainsString( 'remove_cybermaps_branding', $reporting . $settings );
	}
}
