"""Render both public stylesheet variants; source text alone cannot prove consent."""
from pathlib import Path
from lxml import etree

root = Path(__file__).resolve().parents[2]
for kind in ('sitemapindex', 'urlset'):
    document = etree.fromstring(f'<{kind} xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"/>'.encode())
    for filename, credited in (('sitemap.xsl', False), ('sitemap-attribution.xsl', True)):
        transform = etree.XSLT(etree.parse(str(root / 'assets/xsl' / filename)))
        html = str(transform(document))
        assert ('Generated by CYBER MAPS' in html) is credited, (filename, kind)
        assert '<h1>XML Sitemap' in html
        assert 'cybermaps.dev' not in html
print('Index and child sitemap transformations: default off, explicit opt-in only.')
